import type { Metadata } from "next";
import { Noto_Sans_Thai, Prompt, Sarabun } from "next/font/google";
import "../globals.css";

export const notoFont = Noto_Sans_Thai({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap",
  variable: "--font-noto",
});

export const sarabunFont = Sarabun({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap",
  variable: "--font-salabun",
});

export const promptFont = Prompt({
  weight: ["400", "500", "700"],
  subsets: ["thai"],
  display: "swap",
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="th"
    >
      <body className={sarabunFont.className}>
        <h1 className="text-2xl">สวัสดี - root layout header</h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
